language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn test
notifications:
  slack: robtesttravis:VeqfcT6OlTJBhzCIZGbVkfSb
  email:
    recipients:
      - roberto.oro.rowan@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 5f487396-992f-44f2-a23f-b012b1247784
  app: platzi-store-backend-rob
  on:
    repo: robertorw96/platzi-store-backend
